/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/event/Obligation copy 2.vue')['default']
    3: typeof import('./src/components/event/Obligation copy 3.vue')['default']
    copy: typeof import('./src/components/learn/StudyOfPartyHistory copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Obligation: typeof import('./src/components/event/Obligation.vue')['default']
    PartyCourseLearning: typeof import('./src/components/learn/PartyCourseLearning.vue')['default']
    QuotationsLearning: typeof import('./src/components/learn/QuotationsLearning.vue')['default']
    Read: typeof import('./src/components/event/Read.vue')['default']
    Report: typeof import('./src/components/event/Report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/event/Service.vue')['default']
    StudyOfPartyHistory: typeof import('./src/components/learn/StudyOfPartyHistory.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    Work: typeof import('./src/components/Work.vue')['default']
  }
}
